import os
import uuid
import io

from flask import Flask, request, send_file, abort, render_template
from dotenv import load_dotenv
from crypto_utils import encrypt_file, decrypt_file

# =========================
# Load AES key
# =========================
load_dotenv()

AES_SECRET = os.getenv("AES_SECRET")
if not AES_SECRET:
    raise ValueError("AES_SECRET not set")

AES_KEY = AES_SECRET.encode()

# =========================
# Paths
# =========================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

# =========================
# Flask app
# =========================
app = Flask(__name__)

# =========================
# Homepage
# =========================
@app.route("/")
def index():
    return render_template("index.html")

# =========================
# Encrypt & Upload
# =========================
@app.route("/upload", methods=["POST"])
def upload():
    if "file" not in request.files:
        abort(400, "No file provided")

    file = request.files["file"]
    if file.filename == "":
        abort(400, "Empty file")

    plaintext = file.read()
    encrypted = encrypt_file(plaintext, AES_KEY)

    file_id = str(uuid.uuid4())
    path = os.path.join(UPLOAD_DIR, file_id)

    with open(path, "wb") as f:
        f.write(encrypted)

    return render_template("index.html", file_id=file_id)

# =========================
# Download ENCRYPTED file
# =========================
@app.route("/download/<file_id>")
def download_encrypted(file_id):
    path = os.path.join(UPLOAD_DIR, file_id)

    if not os.path.exists(path):
        abort(404, "File not found")

    return send_file(
        path,
        as_attachment=True,
        download_name=f"{file_id}.enc"
    )

# =========================
# Decrypt uploaded encrypted file
# =========================
@app.route("/decrypt", methods=["POST"])
def decrypt_uploaded_file():
    if "enc_file" not in request.files:
        abort(400, "No encrypted file provided")

    encrypted_data = request.files["enc_file"].read()

    try:
        decrypted = decrypt_file(encrypted_data, AES_KEY)
    except ValueError:
        return render_template(
            "index.html",
            error="❌ Invalid encrypted file. Upload a file generated by this portal."
        )

    return send_file(
        io.BytesIO(decrypted),
        as_attachment=True,
        download_name="decrypted_file"
    )

# =========================
# Run
# =========================
if __name__ == "__main__":
    app.run(debug=True)
